config/routes.rb
TestTokbox::Application.routes.draw do
   devise_for :users

   resources :homes
   resources :videos
   
   root :to => 'homes#index'
end

app/models/open_meeting.rb
class OpenMeeting < ActiveRecord::Base
 
  def self.establish_connection
    super(:openmeetings_dev)
  end

  establish_connection
  
  def self.create_user(user)
    sql = ("INSERT INTO users (firstname, lastname, login, password) VALUES ('#{user.firstname}', '#{user.lastname}', '#{user.email}', '#{user.new_password}')")
    connection.execute(sql) 
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :trackable, :validatable, :confirmable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :new_password, :firstname, :lastname, :username, :email, :password, :password_confirmation, :remember_me, :confirmation_token
  attr_accessor :new_password
  
  after_create :make_backup
  
  def make_backup
    OpenMeeting.create_user(self)
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < Devise::SessionsController
  
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_filter :authenticate_user!
  def index
      response = HTTParty.get("http://localhost:5080/openmeetings/services/UserService/getSession/openmeetings/services/UserService/getSession")
      session_id = response["getSessionResponse"]["return"]["session_id"]
#      @course_topic.update_attributes(:tok_sid => session_id)
      uri = URI.parse("http://localhost:5080")
      redirect_to uri.to_s
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/homes/index.html.erb
<h2 class="text-success">
  Welcome to home page
</h2>

<%= link_to "videos", videos_path%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestTokbox</title>
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <div class="container">
      <div class="panel-body">
        <div class="row">
          <p class="notice"><%= notice %></p>
          <p class="alert"><%= alert %></p>
        </div>

        <div class="row">
          <% if current_user %>
            <%= link_to "Logout", destroy_user_session_path, :method => :delete, :class => "btn btn-lg btn-success" %>
          <% else %>
            <%= link_to "Signin", new_user_session_path, :class => "btn btn-lg btn-success" %>
          <% end %>
        </div>
      </div>
      <%= yield %>
    </div>
  </body>
</html>

app/views/videos/index.html.erb
<%= link_to "videos","http://localhost:5080/openmeetings/services/UserService/loginUser?SID=ffbdf15e69d94df83afe363e82baff6e&username=admin&userpass=admin" %>